events {
    worker_connections 1024;
}

http {
    upstream server_backend {
        server server:3001;
    }

    upstream admin_frontend {
        server admin:5173;
    }

    upstream bigscreen_frontend {
        server bigscreen:5174;
    }

    upstream player_frontend {
        server player:5175;
    }

    server {
        listen 80;
        client_max_body_size 3M;

        location /socket.io/ {
            proxy_pass http://server_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://server_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /uploads/ {
            proxy_pass http://server_backend;
        }

        location /join/ {
            proxy_pass http://player_frontend;
            proxy_set_header Host $host;
        }

        location /screen/ {
            proxy_pass http://bigscreen_frontend/;
            proxy_set_header Host $host;
        }

        location /admin/ {
            proxy_pass http://admin_frontend/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://admin_frontend;
            proxy_set_header Host $host;
        }
    }
}
