#!/bin/bash
set -e

echo "🏎️  Decibel Racing — Deploy на Render"
echo ""
echo "Шаг 1: Создайте аккаунт на https://render.com (если нет)"
echo "Шаг 2: Установите Render CLI:"
echo "        brew install render   (Mac)"
echo "        или: curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh"
echo ""
echo "Шаг 3: Авторизуйтесь:  render login"
echo "Шаг 4: Запустите деплой:  render deploy"
echo ""
echo "Или через GitHub (рекомендуется):"
echo "  1. git init && git add . && git commit -m 'init'"
echo "  2. Создайте репо на GitHub и запушьте"
echo "  3. Render Dashboard → New → Blueprint → подключите репо"
echo "  4. Render прочитает render.yaml и задеploит автоматически"
echo ""
echo "После деплоя ваш URL будет вида:"
echo "  https://decibel-racing-xxxx.onrender.com"
echo ""
echo "  Admin:    https://ВАШ-URL.onrender.com/admin/"
echo "  Screen:   https://ВАШ-URL.onrender.com/screen/?room=КОД"
echo "  Player:   https://ВАШ-URL.onrender.com/join/КОД"
echo ""
